# Generated by Django 6.0 on 2026-01-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_last_updated_product_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
